name: Test Installation Scripts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-windows-full-install:
    runs-on: windows-latest
    name: Test Windows Full Installation
    # Only run full install on manual trigger or main branch
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run full Windows installation
        shell: powershell
        run: |
          Write-Host "Running FULL Windows installation test..." -ForegroundColor Cyan
          Write-Host "This will actually install R, RStudio, and packages" -ForegroundColor Gray
          Write-Host ""
          
          # Set execution policy for this session
          Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
          
          # Run the actual installation script
          # Note: In CI, we'll auto-answer "N" to the R experience question if R is in Program Files
          $env:CI = "true"
          .\windows-install-radiant.ps1
          
      - name: Verify installations
        shell: powershell  
        run: |
          Write-Host "Verifying installations..." -ForegroundColor Cyan
          
          # Check R installation
          $RPath = Get-ChildItem "C:\R\R-*\bin\R.exe" -ErrorAction SilentlyContinue | Select-Object -First 1
          if ($RPath) {
              Write-Host "R installed at: $($RPath.FullName)" -ForegroundColor Green
              # Use cmd to avoid PowerShell treating stderr as error
              $RVersionOutput = cmd /c "`"$($RPath.FullName)`" --version 2>&1"
              # Join array output to string and get first line
              $RVersion = ($RVersionOutput -join "`n").Split("`n")[0]
              Write-Host "   Version: $RVersion" -ForegroundColor Gray
          } else {
              Write-Host "R not found in C:\R" -ForegroundColor Red
              # Check if mistakenly in Program Files
              if (Test-Path "${env:ProgramFiles}\R\R-*\bin\R.exe") {
                  Write-Host "R found in Program Files (not recommended)" -ForegroundColor Yellow
              }
              exit 1
          }
          
          # Check RStudio installation
          if (Test-Path "${env:ProgramFiles}\RStudio\rstudio.exe") {
              Write-Host "RStudio installed in Program Files\RStudio" -ForegroundColor Green
          } else {
              Write-Host "RStudio not found" -ForegroundColor Red
              exit 1
          }
          
          # Check 7-Zip installation
          $7ZipPath = Get-ChildItem -Path @(
              "${env:ProgramFiles}\7-Zip\7z.exe",
              "C:\Program Files (x86)\7-Zip\7z.exe"
          ) -ErrorAction SilentlyContinue | Select-Object -First 1
          
          if ($7ZipPath) {
              Write-Host "7-Zip installed at: $7ZipPath" -ForegroundColor Green
          } else {
              Write-Host "7-Zip not found" -ForegroundColor Yellow
          }
          
          # Check if key R packages are installed
          if ($RPath) {
              & $RPath.FullName -e "if ('radiant' %in% rownames(installed.packages())) cat('Radiant package installed\n') else stop('Radiant package not found')"
          }
          
          # Check if pdflatex is available (from TinyTeX)
          $pdflatex = Get-Command pdflatex -ErrorAction SilentlyContinue
          if ($pdflatex) {
              Write-Host "LaTeX (pdflatex) is available at: $($pdflatex.Path)" -ForegroundColor Green
          } else {
              Write-Host "LaTeX (pdflatex) not found (TinyTeX might not be installed)" -ForegroundColor Yellow
          }
          
          Write-Host ""
          Write-Host "Full installation test completed successfully!" -ForegroundColor Green
      
      - name: Test uninstall script
        shell: powershell
        run: |
          Write-Host "Testing uninstall script..." -ForegroundColor Cyan
          
          # Run uninstall script with automatic 'yes' confirmation
          $env:CI = "true"
          # Modify the uninstall script to auto-confirm in CI
          $content = Get-Content .\windows-uninstall-radiant.ps1 -Raw
          $content = $content -replace "Read-Host `"Are you sure you want to uninstall\? Type 'yes' to confirm`"", "`"yes`""
          $content = $content -replace "Read-Host `"Do you want to remove 7-Zip as well\? \(yes/no\)`"", "`"yes`""
          $content = $content -replace "Read-Host$", "# Read-Host"
          $content | Out-File -FilePath .\windows-uninstall-radiant-ci.ps1 -Encoding UTF8
          
          # Run the modified uninstall script
          .\windows-uninstall-radiant-ci.ps1
          
      - name: Verify uninstallation
        shell: powershell
        run: |
          Write-Host "Verifying complete uninstallation..." -ForegroundColor Cyan
          
          $errorsFound = $false
          
          # Check R is removed
          $RPath = Get-ChildItem "C:\R\R-*\bin\R.exe" -ErrorAction SilentlyContinue | Select-Object -First 1
          if ($RPath) {
              Write-Host "[ERROR] R still found at: $($RPath.FullName)" -ForegroundColor Red
              $errorsFound = $true
          } else {
              Write-Host "[OK] R successfully removed" -ForegroundColor Green
          }
          
          # Check RStudio is removed
          $RStudioPaths = @(
              "${env:ProgramFiles}\RStudio\rstudio.exe",
              "${env:LocalAppData}\Programs\RStudio\rstudio.exe"
          )
          foreach ($path in $RStudioPaths) {
              if (Test-Path $path) {
                  Write-Host "[ERROR] RStudio still found at: $path" -ForegroundColor Red
                  $errorsFound = $true
              }
          }
          if (-not $errorsFound) {
              Write-Host "[OK] RStudio successfully removed" -ForegroundColor Green
          }
          
          # Check R libraries are removed
          if (Test-Path "$env:USERPROFILE\Documents\R") {
              Write-Host "[WARNING] R libraries folder still exists" -ForegroundColor Yellow
          } else {
              Write-Host "[OK] R libraries removed" -ForegroundColor Green
          }
          
          # Check 7-Zip is removed (we said yes to remove it)
          $7ZipPath = Get-ChildItem -Path @(
              "${env:ProgramFiles}\7-Zip\7z.exe",
              "${env:ProgramFiles(x86)}\7-Zip\7z.exe"
          ) -ErrorAction SilentlyContinue | Select-Object -First 1
          if ($7ZipPath) {
              Write-Host "[WARNING] 7-Zip still found at: $7ZipPath" -ForegroundColor Yellow
          } else {
              Write-Host "[OK] 7-Zip removed" -ForegroundColor Green
          }
          
          if ($errorsFound) {
              Write-Host ""
              Write-Host "Uninstallation verification FAILED" -ForegroundColor Red
              exit 1
          } else {
              Write-Host ""
              Write-Host "Uninstallation verification PASSED - all components removed!" -ForegroundColor Green
          }

  test-windows:
    runs-on: windows-latest
    name: Test Windows Installer
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test PowerShell script syntax
        shell: powershell
        run: |
          Write-Host "Testing PowerShell script syntax..."
          $null = [System.Management.Automation.PSParser]::Tokenize((Get-Content .\windows-install-radiant.ps1 -Raw), [ref]$null)
          Write-Host "Script syntax is valid"

      - name: Test script in dry-run mode (modified for CI)
        shell: powershell
        run: |
          Write-Host "Creating test version of script..."
          Write-Host "TEST MODE - Checking script logic without installing" -ForegroundColor Cyan
          Write-Host ""
          
          $ErrorActionPreference = "Stop"
          
          # Test temp directory creation
          $TEMP_DIR = New-TemporaryFile | ForEach-Object { Remove-Item $_; New-Item -ItemType Directory -Path $_ }
          Write-Host "Temp directory created: $TEMP_DIR"
          
          # Test R detection logic
          $SystemDrive = $env:SystemDrive
          Write-Host "System drive detected: $SystemDrive"
          
          # Test version checking
          Write-Host "Testing R version check..."
          try {
              $Response = Invoke-WebRequest -Uri "https://cloud.r-project.org/bin/windows/base/release.html" -MaximumRedirection 0 -ErrorAction SilentlyContinue
          } catch {
              if ($_.Exception.Response.StatusCode -eq 302) {
                  $RURL = $_.Exception.Response.Headers.Location.ToString()
                  if ($RURL -match "R-(\d+\.\d+\.\d+)-win.exe") {
                      Write-Host "Latest R version detected: $($matches[1])"
                      Write-Host "Download URL: $RURL"
                  }
              }
          }
          
          Write-Host "Testing RStudio version check..."
          $RStudioPage = Invoke-WebRequest -Uri "https://posit.co/download/rstudio-desktop/" -UseBasicParsing
          if ($RStudioPage.Content -match '//download1\.rstudio\.org/electron/windows/RStudio-([^"]+)\.exe') {
              $RStudioURL = "https:$($matches[0])"
              $Version = $matches[1] -replace '-', '+'
              Write-Host "Latest RStudio version detected: $Version"
              Write-Host "Download URL: $RStudioURL"
          }
          
          # Cleanup
          Remove-Item -Path $TEMP_DIR -Recurse -Force -ErrorAction SilentlyContinue
          Write-Host "Cleanup successful"
          
          Write-Host ""
          Write-Host "All script logic tests passed!" -ForegroundColor Green

      - name: Check required tools availability
        shell: powershell
        run: |
          Write-Host "Checking for required Windows tools..."
          
          # Check if Invoke-WebRequest is available
          if (Get-Command Invoke-WebRequest -ErrorAction SilentlyContinue) {
              Write-Host "Invoke-WebRequest is available"
          } else {
              Write-Host "Invoke-WebRequest is not available"
              exit 1
          }
          
          # Check if we can query Program Files
          if (Test-Path $env:ProgramFiles) {
              Write-Host "Can access Program Files directory"
          }
          
          # Check PowerShell version
          Write-Host "PowerShell version: $($PSVersionTable.PSVersion)"

  test-macos-full-install:
    runs-on: macos-latest
    name: Test macOS Full Installation
    # Only run full install on manual trigger or main branch
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run full macOS installation
        run: |
          echo "Running FULL macOS installation test..."
          echo "This will actually install R, RStudio, and packages"
          echo ""
          
          # Make script executable
          chmod +x macos-install-radiant.sh
          
          # Run the installation script
          # In CI, we may need to handle sudo differently
          export CI=true
          ./macos-install-radiant.sh
          
      - name: Verify installations
        run: |
          echo "Verifying installations..."
          
          # Check R installation
          if command -v R &> /dev/null; then
              R_VERSION=$(R --version 2>/dev/null | head -n1)
              echo "✅ R installed: $R_VERSION"
          else
              echo "❌ R not found"
              exit 1
          fi
          
          # Check RStudio installation
          if [ -d "/Applications/RStudio.app" ]; then
              echo "✅ RStudio installed in /Applications"
              if [ -f "/Applications/RStudio.app/Contents/Info.plist" ]; then
                  RSTUDIO_VERSION=$(defaults read /Applications/RStudio.app/Contents/Info CFBundleShortVersionString 2>/dev/null)
                  echo "   Version: $RSTUDIO_VERSION"
              fi
          else
              echo "❌ RStudio not found in /Applications"
              exit 1
          fi
          
          # Check if radiant package is installed
          R -e "if ('radiant' %in% rownames(installed.packages())) cat('✅ Radiant package installed\n') else stop('❌ Radiant package not found')"
          
          # Check if pdflatex is available (from TinyTeX)
          if command -v pdflatex &> /dev/null; then
              echo "✅ LaTeX (pdflatex) is available"
              pdflatex --version | head -n1
          else
              echo "⚠️  LaTeX (pdflatex) not found (TinyTeX might not be installed)"
          fi
          
          echo ""
          echo "✅ Full macOS installation test completed successfully!"
      
      - name: Test uninstall script
        run: |
          echo "Testing uninstall script..."
          
          # Make uninstall script executable
          chmod +x macos-uninstall-radiant.sh
          
          # Modify the uninstall script to auto-confirm in CI
          sed 's/read -p "Are you sure you want to uninstall? (yes\/no): " -r REPLY/REPLY="yes"/' macos-uninstall-radiant.sh > macos-uninstall-radiant-ci.sh
          chmod +x macos-uninstall-radiant-ci.sh
          
          # Run the modified uninstall script
          export CI=true
          sudo ./macos-uninstall-radiant-ci.sh
          
      - name: Verify uninstallation
        run: |
          echo "Verifying complete uninstallation..."
          
          errors_found=false
          
          # Check R is removed
          if command -v R &> /dev/null; then
              echo "❌ ERROR: R command still available"
              errors_found=true
          else
              echo "✅ R successfully removed"
          fi
          
          # Check R framework is removed
          if [ -d "/Library/Frameworks/R.framework" ]; then
              echo "❌ ERROR: R framework still exists"
              errors_found=true
          else
              echo "✅ R framework removed"
          fi
          
          # Check RStudio is removed
          if [ -d "/Applications/RStudio.app" ]; then
              echo "❌ ERROR: RStudio still found in /Applications"
              errors_found=true
          else
              echo "✅ RStudio successfully removed"
          fi
          
          # Check R libraries are removed
          if [ -d "$HOME/Library/R" ]; then
              echo "⚠️  WARNING: R libraries folder still exists"
          else
              echo "✅ R libraries removed"
          fi
          
          # Check TinyTeX is removed
          if [ -d "$HOME/Library/TinyTeX" ]; then
              echo "⚠️  WARNING: TinyTeX folder still exists"
          else
              echo "✅ TinyTeX removed"
          fi
          
          if [ "$errors_found" = true ]; then
              echo ""
              echo "❌ Uninstallation verification FAILED"
              exit 1
          else
              echo ""
              echo "✅ Uninstallation verification PASSED - all components removed!"
          fi

  test-macos:
    runs-on: macos-latest
    name: Test macOS Installer
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test bash script syntax
        run: |
          echo "Testing bash script syntax..."
          bash -n macos-install-radiant.sh
          echo "✅ Script syntax is valid"

      - name: Test script logic (dry-run)
        run: |
          echo "Testing script logic without installing..."
          
          # Test macOS version check
          echo "Testing macOS version check..."
          macos_version=$(sw_vers -productVersion)
          if [[ $(echo "$macos_version 10.15" | tr " " "\n" | sort -V | head -n1) != "10.15" ]]; then
              echo "❌ macOS version check failed"
              exit 1
          fi
          echo "✅ macOS version check passed: $macos_version"
          
          # Test R version detection
          echo "Testing R version detection from CRAN..."
          LATEST_R_VERSION=$(curl -s "https://cloud.r-project.org/bin/macosx/" | grep -o 'R-[0-9]\+\.[0-9]\+\.[0-9]\+' | head -n1 | cut -d'-' -f2)
          if [[ -n "$LATEST_R_VERSION" ]]; then
              echo "✅ Latest R version detected: $LATEST_R_VERSION"
          else
              echo "❌ Could not detect R version"
              exit 1
          fi
          
          # Test RStudio URL extraction
          echo "Testing RStudio version detection..."
          RSTUDIO_PAGE=$(curl -s "https://posit.co/download/rstudio-desktop/")
          RSTUDIO_URL="https:$(echo "$RSTUDIO_PAGE" | grep -o '//download1\.rstudio\.org/electron/macos/RStudio-[^"]*\.dmg' | head -n1)"
          if [[ "$RSTUDIO_URL" != "https:" ]] && [[ -n "$RSTUDIO_URL" ]]; then
              echo "✅ RStudio URL detected: $RSTUDIO_URL"
          else
              echo "❌ Could not detect RStudio URL"
              exit 1
          fi
          
          echo ""
          echo "✅ All macOS script logic tests passed!"

      - name: Check required tools availability
        run: |
          echo "Checking for required macOS tools..."
          
          # Check for curl
          if command -v curl &> /dev/null; then
              echo "✅ curl is available"
          else
              echo "❌ curl is not available"
              exit 1
          fi
          
          # Check for hdiutil (for mounting DMGs)
          if command -v hdiutil &> /dev/null; then
              echo "✅ hdiutil is available"
          else
              echo "❌ hdiutil is not available"
              exit 1
          fi
          
          # Check for sw_vers
          if command -v sw_vers &> /dev/null; then
              echo "✅ sw_vers is available: $(sw_vers -productVersion)"
          else
              echo "❌ sw_vers is not available"
              exit 1
          fi